"""Interactive onboarding wizard — helps users configure API keys and routing profile.

Run as a CLI entry point (``chuzom-onboard``) to launch the setup wizard.
The wizard reads any existing ``.env`` in the current directory, prompts the
user to add or update API keys for each supported provider, selects a routing
profile, and writes the final ``.env`` file.
"""

from __future__ import annotations

import sys
from pathlib import Path

PROVIDERS = {
    "GEMINI_API_KEY": {
        "name": "Google Gemini",
        "url": "https://aistudio.google.com/apikey",
        "models": "Gemini 2.0 Flash, Gemini 2.5 Pro",
    },
    "OPENAI_API_KEY": {
        "name": "OpenAI",
        "url": "https://platform.openai.com/api-keys",
        "models": "GPT-4o, GPT-4o-mini, o3",
    },
    "PERPLEXITY_API_KEY": {
        "name": "Perplexity",
        "url": "https://www.perplexity.ai/settings/api",
        "models": "Sonar, Sonar Pro (search-augmented)",
    },
}
"""Provider definitions for the onboarding wizard.

Each key is an environment variable name; the value dict contains the
human-readable provider name, the signup URL where the user can obtain an
API key, and a summary of available models.  The wizard iterates this dict
to present each provider in turn.
"""

PROFILES = {
    "budget": "Cheapest models — Gemini Flash, GPT-4o-mini, Sonar",
    "balanced": "Best quality/cost ratio — Gemini Pro, GPT-4o, Sonar Pro",
    "premium": "Best available — o3, Gemini 2.5 Pro, Sonar Pro",
}
"""Available routing profiles and their human-readable descriptions.

The selected profile is written to ``.env`` as ``CHUZOM_PROFILE`` and
controls which model tier the router defaults to for each task type.
"""


def main() -> None:
    """Run the interactive CLI onboarding wizard for Chuzom.

    Flow:
        1. Read existing ``.env`` in the current directory (if present) to
           pre-populate current key values.
        2. For each provider in ``PROVIDERS``, show its name, available
           models, and signup URL.  If a key already exists, offer to keep
           it; otherwise prompt for a new key (or skip).
        3. Prompt for a routing profile selection from ``PROFILES``,
           defaulting to the previously configured profile or ``"balanced"``.
        4. Write all keys and the selected profile to ``.env`` with
           comments linking to each provider's signup page.
        5. Print a summary of configured vs. skipped providers and next
           steps.  Exit with code 1 if no providers were configured.
    """
    env_path = Path.cwd() / ".env"
    print("\n╔══════════════════════════════════════════╗")
    print("║        Chuzom — Setup Wizard         ║")
    print("╚══════════════════════════════════════════╝\n")

    # Load existing .env if present
    existing: dict[str, str] = {}
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, val = line.partition("=")
                existing[key.strip()] = val.strip()
        print(f"Found existing .env at {env_path}\n")

    keys: dict[str, str] = {}

    for env_var, info in PROVIDERS.items():
        current = existing.get(env_var, "")
        masked = f"{'*' * (len(current) - 4)}{current[-4:]}" if len(current) > 4 else ""

        print(f"── {info['name']} ──")
        print(f"   Models: {info['models']}")
        print(f"   Get key: {info['url']}")

        if masked:
            print(f"   Current: {masked}")
            keep = input("   Keep existing key? [Y/n]: ").strip().lower()
            if keep in ("", "y", "yes"):
                keys[env_var] = current
                print()
                continue

        key = input(f"   Enter {info['name']} API key (or press Enter to skip): ").strip()
        keys[env_var] = key
        print()

    # Profile selection
    print("── Routing Profile ──")
    for name, desc in PROFILES.items():
        print(f"   {name:10s} — {desc}")

    current_profile = existing.get("CHUZOM_PROFILE", "balanced")
    profile = (
        input(f"\n   Choose profile [{current_profile}]: ").strip().lower()
        or current_profile
    )
    if profile not in PROFILES:
        print(f"   Invalid profile '{profile}', defaulting to 'balanced'")
        profile = "balanced"

    # Write .env
    lines = [
        "# Chuzom Configuration",
        "# Generated by chuzom-onboard",
        "",
    ]
    for env_var, info in PROVIDERS.items():
        lines.append(f"# {info['name']} ({info['url']})")
        lines.append(f"{env_var}={keys.get(env_var, '')}")
        lines.append("")

    lines.append(f"CHUZOM_PROFILE={profile}")

    env_path.write_text("\n".join(lines) + "\n")

    # Summary
    configured = [info["name"] for var, info in PROVIDERS.items() if keys.get(var)]
    skipped = [info["name"] for var, info in PROVIDERS.items() if not keys.get(var)]

    print("\n╔══════════════════════════════════════════╗")
    print("║              Setup Complete!              ║")
    print("╚══════════════════════════════════════════╝")
    print(f"\n   .env written to: {env_path}")
    print(f"   Profile: {profile}")
    print(f"   Configured: {', '.join(configured) or 'none'}")
    if skipped:
        print(f"   Skipped: {', '.join(skipped)}")
    print("\n   You need at least 1 provider configured to use Chuzom.")

    if not configured:
        print("\n   ⚠ No API keys configured! Run this again when you have keys.")
        sys.exit(1)

    # Subscription detection (D3)
    sub_current = existing.get("CHUZOM_CLAUDE_SUBSCRIPTION", "")
    sub_prompt = "   Do you have a Claude Pro/Max subscription? [y/n]: "
    if sub_current.lower() in ("true", "1", "yes"):
        keep_sub = input("   You have subscription mode enabled. Keep it? [Y/n]: ").strip().lower()
        if keep_sub in ("", "y", "yes"):
            with open(env_path, "a") as f:
                f.write(f"CHUZOM_CLAUDE_SUBSCRIPTION=true\n")
    else:
        sub_answer = input(sub_prompt).strip().lower()
        if sub_answer in ("y", "yes"):
            with open(env_path, "a") as f:
                f.write(f"CHUZOM_CLAUDE_SUBSCRIPTION=true\n")
            print("   Subscription mode enabled — Claude quota will be tracked and saved.")

    # G2: Initialize ~/.chuzom/ directory and usage database so the first
    # `chuzom status` / `chuzom savings-report` command doesn't fail on a
    # missing directory. Done here so it happens before hooks start writing.
    import sqlite3 as _sqlite3
    from pathlib import Path as _Path
    _state_dir = _Path.home() / ".chuzom"
    try:
        _state_dir.mkdir(parents=True, exist_ok=True)
        _usage_db = _state_dir / "usage.db"
        if not _usage_db.exists():
            _conn = _sqlite3.connect(str(_usage_db))
            _conn.execute(
                "CREATE TABLE IF NOT EXISTS usage ("
                "  id INTEGER PRIMARY KEY AUTOINCREMENT,"
                "  ts REAL NOT NULL,"
                "  session_id TEXT,"
                "  task_type TEXT,"
                "  model TEXT,"
                "  provider TEXT,"
                "  input_tokens INTEGER DEFAULT 0,"
                "  output_tokens INTEGER DEFAULT 0,"
                "  latency_ms INTEGER DEFAULT 0,"
                "  cost_usd REAL DEFAULT 0.0,"
                "  saved_usd REAL DEFAULT 0.0"
                ")"
            )
            _conn.commit()
            _conn.close()
            print(f"   ✓ Initialized ~/.chuzom/usage.db")
    except Exception as _g2_err:
        print(f"   ⚠ Could not initialize ~/.chuzom/: {_g2_err}")

    # Auto-install hooks (A1) — the single most important step for new users
    print("\n── Installing Chuzom hooks into Claude Code ──")
    try:
        from chuzom.install_hooks import install as _install_hooks
        install_actions = _install_hooks()
        for action in install_actions:
            print(f"   ✓ {action}")
        print("   Hooks installed successfully.")
    except Exception as exc:
        print(f"   ⚠ Hook installation failed: {exc}")
        print("   Fix manually: run `chuzom install` in your terminal.")

    print("\n   Next: Open Claude Code — routing is now active.\n")


if __name__ == "__main__":
    main()
