# SPDX-License-Identifier: MIT
"""Proxy eval set — self-generated, RA-INDEPENDENT calibration corpus.

Compliance (see memory ra-compliance-label-provenance / PR-155):
  Every item is generated by code with a COMPUTED answer. Nothing is drawn from
  RouterArena's split, its 23 source datasets, its accuracy/judge/oracle values,
  or RouterBench. Ground truth is owned by us → fitting the escalation rule's
  thresholds on this corpus can never be "tuning on RA data".

Shape mirrors RA structurally (multiple general DOMAINS × 3 Bloom DIFFICULTIES ×
several METRIC types) so the proxy's agreement/difficulty dynamics — and hence
the arena score it yields — track the real benchmark, without copying it.

Each item: {id, domain, difficulty, metric, prompt, answer, gen}
  metric ∈ {math, mcq, exact}  → scored by sandbox.grader.grade_by_metric
  difficulty ∈ {easy, medium, hard}
  domain ∈ 9 general axes (our taxonomy, NOT RA's 44 categories)

KNOWN GAP (documented, not hidden): free-text generation / translation (METEOR)
is under-covered because a computed gold reference can't be self-generated for
it. The live-signal escalation rule is domain-general, so threshold calibration
does not depend on that axis; translation escalation TARGETS are handled by the
capability map, whose multilingual axis needs a separately-sourced, RA-independent
parallel corpus (flagged in tasks, not faked here).
"""
from __future__ import annotations

import math
import random

# ── Domains (9 general axes — our own taxonomy) ───────────────────────────────
ARITH, NUMTH, ALGEBRA, COMBIN, LOGIC, SEQ, QUANT, STRINGS, UNITS = (
    "Arithmetic", "NumberTheory", "Algebra", "Combinatorics", "LogicReasoning",
    "Sequences", "QuantitativeWord", "StringManipulation", "UnitsConversion",
)


# ── Numeric cores: return (question_text, correct_number_str) ─────────────────
def c_add(r):
    a, b = r.randint(2, 99), r.randint(2, 99)
    return f"Compute {a} + {b}.", str(a + b)


def c_mul(r):
    a, b = r.randint(12, 99), r.randint(12, 99)
    return f"Compute {a} × {b}.", str(a * b)


def c_percent(r):
    p, n = r.choice([10, 15, 20, 25, 40]), r.choice([40, 60, 80, 120, 200])
    return f"What is {p}% of {n}?", str(int(p * n / 100))


def c_divisors(r):
    n = r.choice([12, 18, 24, 36, 48, 60, 72, 100, 120])
    return f"How many positive divisors does {n} have?", str(sum(1 for i in range(1, n + 1) if n % i == 0))


def c_modular(r):
    n, m = r.randint(100, 999), r.choice([7, 9, 11, 13])
    return f"What is the remainder when {n} is divided by {m}?", str(n % m)


def c_gcd(r):
    a, b = r.randint(12, 400), r.randint(12, 400)
    return f"What is the greatest common divisor of {a} and {b}?", str(math.gcd(a, b))


def c_primefactor(r):
    n = r.choice([84, 90, 126, 132, 156, 198, 210, 264, 315, 429, 546, 630])
    m, d, fac = n, 2, []
    while d * d <= m:
        while m % d == 0:
            fac.append(d); m //= d
        d += 1
    if m > 1:
        fac.append(m)
    return f"What is the largest prime factor of {n}?", str(max(fac))


def c_linear(r):
    x, y = r.randint(2, 20), r.randint(2, 20)
    a1, b1, a2, b2 = (r.randint(1, 5) for _ in range(4))
    if a1 * b2 - a2 * b1 == 0:
        return c_linear(r)
    c1, c2 = a1 * x + b1 * y, a2 * x + b2 * y
    return f"Solve for x: {a1}x + {b1}y = {c1} and {a2}x + {b2}y = {c2}.", str(x)


def c_combin(r):
    n, k = r.randint(6, 14), r.randint(2, 5)
    return f"How many ways can you choose {k} items from {n} distinct items (order irrelevant)?", str(math.comb(n, k))


def c_seq(r):
    s, st = r.randint(1, 5), r.randint(2, 6)
    seq = [s + st * i + i * i for i in range(4)]
    return f"What is the next number in the sequence {', '.join(map(str, seq))}, ?", str(s + st * 4 + 16)


def c_fib(r):
    a0, b0 = r.randint(1, 5), r.randint(1, 5)
    n = r.choice([9, 10, 11, 12])
    a, b = a0, b0
    for _ in range(n - 2):
        a, b = b, a + b
    return f"A sequence starts {a0}, {b0}; each term is the sum of the previous two. What is term {n}?", str(b)


def c_speed(r):
    d, h = r.choice([60, 90, 120, 150, 180]), r.choice([2, 3])
    return f"A train travels {d} miles in {h} hours. What is its speed in mph?", str(d // h)


def c_work(r):
    a, b = r.choice([4, 6, 8, 12]), r.choice([4, 6, 8, 12])
    if a == b:
        return c_work(r)
    return (f"Pipe A fills a tank in {a} h alone, pipe B in {b} h alone. Together, how many hours to fill it? "
            f"(2 decimal places)", f"{1 / (1 / a + 1 / b):.2f}")


def c_interest(r):
    p, rate, t = r.choice([100, 200, 500, 1000]), r.choice([5, 10, 20]), r.choice([2, 3])
    return (f"${p} invested at {rate}% annual compound interest for {t} years. Final amount to the nearest dollar?",
            str(round(p * (1 + rate / 100) ** t)))


def c_logic(r):
    # Deterministic knights/liars-style with a computed unique answer.
    names = r.sample(["Ann", "Bob", "Cy", "Dee", "Eve"], 3)
    truth = r.choice(names)  # the one telling the truth
    who = r.choice(names)
    ans = "Yes" if who == truth else "No"
    return (f"Exactly one of {', '.join(names)} always tells the truth: it is {truth}. "
            f"Does {who} always tell the truth? Answer Yes or No.", ans)


# ── String cores: return (question_text, correct_string) ──────────────────────
def s_reverse(r):
    w = r.choice(["router", "cascade", "gateway", "signal", "vector", "kernel", "entropy", "probe"])
    return f"Reverse the string '{w}'.", w[::-1]


def s_base(r):
    n, base = r.randint(50, 500), r.choice([2, 8, 16])
    digs, m, out = "0123456789ABCDEF", r.randint(50, 500), ""
    m = n
    while m:
        out = digs[m % base] + out; m //= base
    return f"Convert decimal {n} to base {base} (digits only, no prefix).", out


def s_nth_word(r):
    words = r.sample(["apple", "banana", "cherry", "date", "elder", "fig", "grape", "kiwi"], 5)
    i = r.randint(1, 5)
    ordinal = {1: "first", 2: "second", 3: "third", 4: "fourth", 5: "fifth"}[i]
    return f"In the list [{', '.join(words)}], what is the {ordinal} word?", words[i - 1]


# ── Generator registry: (fn, domain, difficulty, base_metric) ─────────────────
# base_metric is the NATIVE metric; math/exact cores can also be wrapped as MCQ.
_NUMERIC = [
    (c_add, ARITH, "easy"), (c_percent, ARITH, "easy"),
    (c_mul, ARITH, "medium"), (c_divisors, NUMTH, "medium"),
    (c_modular, NUMTH, "medium"), (c_speed, QUANT, "medium"),
    (c_seq, SEQ, "medium"),
    (c_gcd, NUMTH, "hard"), (c_primefactor, NUMTH, "hard"),
    (c_linear, ALGEBRA, "hard"), (c_combin, COMBIN, "hard"),
    (c_fib, SEQ, "hard"), (c_work, QUANT, "hard"), (c_interest, QUANT, "hard"),
]
_STRING = [
    (s_reverse, STRINGS, "easy"), (s_nth_word, STRINGS, "easy"),
    (s_base, UNITS, "medium"),
]
_MCQ_CORES = [  # numeric/logic cores presented as 4-option MCQ
    (c_add, ARITH, "easy"), (c_percent, ARITH, "easy"),
    (c_divisors, NUMTH, "medium"), (c_logic, LOGIC, "medium"),
    (c_gcd, NUMTH, "hard"), (c_combin, COMBIN, "hard"), (c_primefactor, NUMTH, "hard"),
]


def _mcq_options(r, correct):
    """Build 4 distinct options incl. correct; return (prompt_body, correct_letter)."""
    opts = {correct}
    try:
        cv = int(correct)
        for cand in (cv + 1, cv - 1, cv + r.choice([2, 3, 5, 10]),
                     cv - r.choice([2, 3, 4]), cv * 2, (cv // 2 if cv > 1 else cv + 7)):
            if len(opts) >= 4:
                break
            if cand >= 0 and str(cand) != correct:
                opts.add(str(cand))
    except ValueError:
        for cand in ("Yes", "No", "Maybe", "Unknown", correct[::-1]):
            if len(opts) >= 4:
                break
            if cand != correct:
                opts.add(cand)
    while len(opts) < 4:
        opts.add(str(r.randint(2, 999)))
    opts = list(opts)[:4]
    r.shuffle(opts)
    letters = "ABCD"
    body = "  ".join(f"{letters[i]}) {o}" for i, o in enumerate(opts))
    return body, letters[opts.index(correct)]


def _make(r, fn, domain, difficulty, metric, idx):
    q, ans = fn(r)
    if metric == "math":
        prompt = f"{q} Put your final answer in \\boxed{{}}."
        gold = ans
    elif metric == "exact":
        prompt = f"{q} Put your final answer in \\boxed{{}}."
        gold = ans
    elif metric == "mcq":
        body, letter = _mcq_options(r, ans)
        prompt = f"{q}\n{body}\nAnswer with \\boxed{{X}} where X is the correct option letter."
        gold = letter
    else:
        raise ValueError(metric)
    return {"id": f"px-{idx:05d}", "domain": domain, "difficulty": difficulty,
            "metric": metric, "prompt": prompt, "answer": gold, "gen": fn.__name__}


def generate_proxy(per_stratum: int = 8, seed: int = 20260706) -> list[dict]:
    """Balanced proxy across (generator × metric-variant), deduped by prompt.

    per_stratum items per generator-variant. Numeric cores appear as both `math`
    and `mcq`; string cores as `exact`; MCQ-only cores as `mcq`.
    """
    r = random.Random(seed)
    out, seen, idx = [], set(), 0
    variants: list[tuple] = (
        [(fn, d, diff, "math") for fn, d, diff in _NUMERIC]
        + [(fn, d, diff, "exact") for fn, d, diff in _STRING]
        + [(fn, d, diff, "mcq") for fn, d, diff in _MCQ_CORES]
    )
    for fn, domain, difficulty, metric in variants:
        made = 0
        attempts = 0
        while made < per_stratum and attempts < per_stratum * 40:
            attempts += 1
            item = _make(r, fn, domain, difficulty, metric, idx)
            if item["prompt"] in seen:
                continue
            seen.add(item["prompt"])
            out.append(item)
            idx += 1
            made += 1
    return out


if __name__ == "__main__":
    import json
    from collections import Counter

    recs = generate_proxy(per_stratum=8)
    print(f"total items: {len(recs)}")
    print("by difficulty:", dict(Counter(x["difficulty"] for x in recs)))
    print("by metric    :", dict(Counter(x["metric"] for x in recs)))
    print("by domain    :", dict(Counter(x["domain"] for x in recs)))
    print("\nsample items:")
    for x in recs[:2] + recs[-2:]:
        print(json.dumps(x, indent=2))

    # Self-grade a correct and a wrong answer through the real RA grader.
    from grader import Grader
    g = Grader()
    ok = [x for x in recs if x["metric"] == "mcq"][0]
    print("\ngrade correct mcq:", g.grade_by_metric(fr"\boxed{{{ok['answer']}}}", ok["answer"], "mcq"))
    print("grade wrong   mcq:", g.grade_by_metric(r"\boxed{Z}", ok["answer"], "mcq"))
    m = [x for x in recs if x["metric"] == "math"][0]
    print("grade correct math:", g.grade_by_metric(fr"\boxed{{{m['answer']}}}", m["answer"], "math"))
