#!/usr/bin/env python3
"""G-C — the acceptance criteria must not change under the executor.

18_REMEDIATION_EXECUTION_PLAN.md states the rule twice:

    "Criteria are hashed before the run (sha256 of the WP's criteria block) and
     re-verified after. A changed hash = automatic FAIL."          (line 34)

    "Pre-register and hash the acceptance check before execution; re-verify the
     hash after. The executor cannot edit the oracle it is graded against."
                                                                   (line 411)

and G-C makes a mismatch a disqualifier: "Any acceptance-criteria hash mismatch
-> WP FAILS".

**No hash was ever computed.** G-C was therefore a gate that could not fire --
the same defect class this audit found in `unregistered()` and
`lint_tool_surface.py`: something shaped like a check, reporting nothing,
counted as protection. This script is its implementation.

WHAT THIS CAN AND CANNOT PROVE
------------------------------
It is honest about three limits, because a gate that overclaims is worse than a
missing one:

1. **It is retroactive, and retroactivity does not work.** The manifest was
   created 2026-08-12, AFTER WP-00..WP-15 had already executed. It cannot show
   that the criteria for those work packages were unmodified while they ran. It
   binds WP-16 onward. Anyone reading a "G-C PASS" for an earlier WP should read
   it as "unchanged since the manifest", never as "unchanged during execution".

2. **It does not stop a determined executor.** Whoever can edit the criteria can
   re-run this with --write. The real protection is that the audit documents are
   now TRACKED: an edit shows up in `git log -p` and in review. What the manifest
   adds is that editing an oracle now requires a second, deliberate, visible act
   instead of a silent one.

3. **It hashes whole files, not criteria blocks.** The plan says "sha256 of the
   WP's criteria block". Per-block hashing was rejected: it needs a parser for
   the block boundaries, and a parser bug would silently narrow what is covered
   -- exactly the under-reporting failure the env registry's scanner blind spot
   demonstrated. Whole-file hashing cannot under-report. It over-reports instead:
   a typo fix in unrelated prose trips the gate and must be re-baselined
   deliberately. That direction of failure is the safe one.

Usage:
    python scripts/verify_criteria_hashes.py            # verify, exit 1 on drift
    python scripts/verify_criteria_hashes.py --write    # re-baseline (deliberate)
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AUDIT = ROOT / ".chuzom" / "zero-tolerance-audit"
MANIFEST = AUDIT / "CRITERIA_MANIFEST.sha256"

#: Excluded from git for size (two 61M usage.db captures from RED2's
#: unknown-vs-zero reproduction). Their hashes ARE recorded, so the evidence
#: stays checkable by anyone who still holds the files -- "too big to commit"
#: must not become "unverifiable".
_UNTRACKED_SUFFIXES = (".db", ".db-shm", ".db-wal")


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _audit_files() -> list[Path]:
    """Every file under the audit directory, manifest itself excluded.

    The manifest cannot hash itself; a self-referential entry would either never
    match or be excluded from its own check, and both read as passing.
    """
    return sorted(
        p
        for p in AUDIT.rglob("*")
        if p.is_file() and p != MANIFEST and not p.name.startswith(".DS_Store")
    )


def _entries() -> list[tuple[str, str, bool]]:
    out = []
    for path in _audit_files():
        rel = str(path.relative_to(AUDIT))
        untracked = path.suffix in _UNTRACKED_SUFFIXES
        out.append((_sha256(path), rel, untracked))
    return out


def write_manifest() -> int:
    entries = _entries()
    lines = [
        "# G-C acceptance-criteria manifest (sha256).",
        "# Generated by scripts/verify_criteria_hashes.py --write.",
        "#",
        "# Entries marked [untracked] are gitignored for size; their hash is",
        "# recorded so the evidence stays checkable by anyone holding the files.",
        "#",
        "# THIS MANIFEST IS RETROACTIVE: created after WP-00..WP-15 executed, so",
        "# it binds WP-16 onward and cannot attest to what came before.",
        "",
    ]
    for digest, rel, untracked in entries:
        mark = "  [untracked]" if untracked else ""
        lines.append(f"{digest}  {rel}{mark}")
    MANIFEST.write_text("\n".join(lines) + "\n")
    tracked = sum(1 for _, _, u in entries if not u)
    print(f"wrote {MANIFEST.relative_to(ROOT)}: {tracked} tracked, "
          f"{len(entries) - tracked} untracked-by-size")
    return 0


def _parse_manifest() -> dict[str, str]:
    recorded: dict[str, str] = {}
    for line in MANIFEST.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        digest, _, rest = line.partition("  ")
        rel = rest.replace("  [untracked]", "").strip()
        recorded[rel] = digest
    return recorded


def verify() -> int:
    if not MANIFEST.exists():
        print(f"FAIL: no manifest at {MANIFEST.relative_to(ROOT)}. G-C cannot be "
              f"evaluated; run --write to baseline.", file=sys.stderr)
        return 1

    recorded = _parse_manifest()
    if not recorded:
        # Guards the guard: an empty manifest would make every comparison below
        # vacuous and print a clean PASS. Same shape as the probe that reported
        # "0/6 reproductions" while measuring nothing.
        print("FAIL: manifest parsed to zero entries -- it cannot detect drift.",
              file=sys.stderr)
        return 1

    actual = {rel: digest for digest, rel, _ in _entries()}

    changed = sorted(
        r for r in recorded.keys() & actual.keys() if recorded[r] != actual[r]
    )
    added = sorted(actual.keys() - recorded.keys())
    missing = sorted(recorded.keys() - actual.keys())

    if not (changed or added or missing):
        print(f"G-C OK: {len(recorded)} audit artifacts match the manifest.")
        return 0

    for rel in changed:
        print(f"CHANGED since baseline: {rel}", file=sys.stderr)
    for rel in added:
        print(f"NEW, unrecorded artifact: {rel}", file=sys.stderr)
    for rel in missing:
        # A deleted criteria file is the loudest possible version of the defect
        # G-C exists to catch, so it is a failure, not a warning.
        print(f"MISSING (recorded but gone): {rel}", file=sys.stderr)
    print(
        "\nG-C FAIL. If a change was deliberate, re-baseline with --write IN ITS "
        "OWN COMMIT so the edit to the oracle is visible in review.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(write_manifest() if "--write" in sys.argv[1:] else verify())
